language: node_js
node_js:
- node
cache: npm
before_script: npm run build
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: S3tdM0M5yJGQcbquZjtuluqxKNHAsTn/Vt0uXTtGCPKclc34ySnIpecJ6PAT8hOyT3S3RFEZYxSIB1VvskGnupCNLwJbznRZH47Xkkqmzb3CbAiKZNIrBmU06y6jj+m1lFblkuuqGxXXgmBvkJQuk/CyiFh5yfTlBpGTHSKq5vSQj7564IgSgrto8K76+3q2eM4M+JDwaMMiYpTZKKCp1Sg5LUTHVRCFiS/IFLV6z/RMf1eIT63mxDwVubyQHtwQDBUX2j+j7ScbqKEJt/8rRoPd1H3rzkdncCWI1jQkno2Dqor0FL2JO2ZdD9CNtYloJtRji+PI6R/5HGkruYfMwKvzKbibDgKKdzcNK2bGfVsP3f8pPB3Qp1KzlqqaVdU7icLbswrK985oSzbXewhupdjaorBXJ7fSrKlkdhZe770tc3bA0dcyLVc1wCUJvgz5AIVRDkSNMIkRRYzkN5S3qdYH8VfCME555niUgj9OIi9NvoDIojMoKPxdQ+bsXrLsMArwe3WalAcNJJn4s+U6cXy8Ujtjf6WxyI3tnU6i3lbEgPHbWtUJdLP2/mbNpkd2NXAYSSCILH89RgZ2S/SRh0FdkmmYwRyBoh7BmVVdiIiOh+Cx+7auU3F7CRdlh/sS+SOjLIaxkDPnBRXHDNTcWNmVk2AVkbMOPPq8/GAkn0Y=
