[[redirects]]
    from = "/blog/2019/05/29/antipatrones-react"
    to = "/blog/antipatrones-react"
    status = 301
    force = true
[[redirects]]
    from = "/blog/2018/06/25/un-vistazo-rapido-a-tailwindcss"
    to = "/blog/un-vistazo-rapido-a-tailwindcss"
    status = 301
    force = true
[[redirects]]
    from = "/blog/2018/03/14/configura-tu-aplicacion-de-react-con-sass"
    to = "/blog/configura-tu-aplicacion-de-react-con-sass"
    status = 301
    force = true
[[redirects]]
    from = "/blog/2018/02/05/que-es-flux-y-por-donde-comenzar"
    to = "/blog/que-es-flux-y-por-donde-comenzar"
    status = 301
    force = true
[[redirects]]
    from = "/blog/2018/02/09/api-rest-para-pruebas"
    to = "/blog/api-rest-para-pruebas"
    status = 301
    force = true